# Generated by Django 6.0.2 on 2026-02-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petportalmeta',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='portal_pet_photos/%Y/%m/'),
        ),
    ]
