# Generated by Django 6.0.2 on 2026-02-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingbehavior',
            name='recent_change_4_weeks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedingbehavior',
            name='recent_change_4_weeks_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodpreferences',
            name='brands_to_avoid_detailed',
            field=models.TextField(blank=True, verbose_name='Brands to avoid with reasons'),
        ),
        migrations.AlterField(
            model_name='feedingbehavior',
            name='bowl_material',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='feedingbehavior',
            name='bowl_type',
            field=models.TextField(blank=True, help_text='Comma-separated bowl types'),
        ),
        migrations.AlterField(
            model_name='feedingbehavior',
            name='water_bowl_material',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
