# Generated by Django 6.0.2 on 2026-02-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0002_feedingbehavior_recent_change_4_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingbehavior',
            name='bowl_material_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedingbehavior',
            name='bowl_type_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feedingbehavior',
            name='water_bowl_material_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedingbehavior',
            name='bowl_material',
            field=models.TextField(blank=True, help_text='Comma-separated materials'),
        ),
        migrations.AlterField(
            model_name='feedingbehavior',
            name='water_bowl_material',
            field=models.TextField(blank=True, help_text='Comma-separated water bowl materials'),
        ),
        migrations.AlterField(
            model_name='feedingbehavior',
            name='water_bowl_type',
            field=models.TextField(blank=True, help_text='Comma-separated water bowl types'),
        ),
    ]
