# Generated by Django 6.0.2 on 2026-02-14 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0003_feedingbehavior_bowl_material_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.TextField(blank=True, help_text='Comma-separated: veterinarian, breeder, pet_store, friend_family, book_magazine, internet')),
                ('other_source', models.CharField(blank=True, max_length=200)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advice_source', to='intake_form.pet')),
            ],
        ),
        migrations.CreateModel(
            name='BrandToAvoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands_to_avoid', to='intake_form.pet')),
            ],
            options={
                'verbose_name': 'Brand To Avoid',
                'verbose_name_plural': 'Brands To Avoid',
            },
        ),
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_chronic', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_condition', to='intake_form.pet')),
            ],
        ),
        migrations.CreateModel(
            name='TreatPreferenceInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.TextField(blank=True, help_text='Comma-separated: commercial_store, dehydrated, raw_bone, homemade_cooked')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treat_plan_preferences', to='intake_form.pet')),
            ],
        ),
    ]
