# Generated by Django 6.0.2 on 2026-02-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0004_advicesource_brandtoavoid_chroniccondition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Current Weight (kg)'),
        ),
    ]
