# Generated by Django 6.0.2 on 2026-02-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0005_alter_pet_current_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('blood_work', 'Blood Work / Lab Reports'), ('diagnostic_imaging', 'Diagnostic Imaging Reports')], max_length=30)),
                ('file', models.FileField(upload_to='vet_uploads/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_uploads', to='intake_form.pet')),
            ],
            options={
                'verbose_name': 'Vet Upload',
                'verbose_name_plural': 'Vet Uploads',
                'ordering': ['category', '-uploaded_at'],
            },
        ),
    ]
