# Generated by Django 6.0.2 on 2026-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0007_homemadedietquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='brands_to_avoid_rows',
            field=models.TextField(blank=True, help_text='JSON list of brand/reason rows'),
        ),
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='homemade_diet_rows',
            field=models.TextField(blank=True, help_text='JSON list of homemade diet table rows'),
        ),
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='treat_plan_preferences',
            field=models.TextField(blank=True, help_text='Comma-separated selected treat preferences'),
        ),
    ]
