# Generated by Django 6.0.2 on 2026-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0008_homemadedietquestionnaire_brands_to_avoid_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='questionnaire_payload',
            field=models.TextField(blank=True, help_text='Raw JSON payload of full questionnaire submission'),
        ),
    ]
