# Generated by Django 6.0.2 on 2026-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0009_homemadedietquestionnaire_questionnaire_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='q1_novel_protein',
            field=models.TextField(blank=True, help_text='JSON row for Q1 Novel Protein Spp selection'),
        ),
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='q1_protein_matrix',
            field=models.TextField(blank=True, help_text='JSON matrix for Q1 protein ingredient selections'),
        ),
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='q2_other_proteins',
            field=models.TextField(blank=True, help_text='JSON rows for Q2 additional protein sources'),
        ),
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='q3_carb_fat_fibre_matrix',
            field=models.TextField(blank=True, help_text='JSON matrix for Q3 carbohydrate/fat/fibre/veggie selections'),
        ),
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='q4_other_carb_fat_fibre',
            field=models.TextField(blank=True, help_text='JSON rows for Q4 additional carb/fat/fibre/veggie sources'),
        ),
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='q5_food_refusal',
            field=models.TextField(blank=True, help_text='JSON rows for Q5 foods pet will not eat and reasons'),
        ),
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='q6_palatable_options',
            field=models.TextField(blank=True, help_text='JSON rows for Q6 preferred palatable options'),
        ),
    ]
