# Generated by Django 6.0.2 on 2026-02-17 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0010_homemadedietquestionnaire_q1_novel_protein_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_history_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homemadedietquestionnaire',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homemade_questionnaire_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petparent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_parent_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vetupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petparent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
