# Generated by Django 6.0.2 on 2026-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_form', '0013_vetformaccesslink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreConsultSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_city', models.CharField(blank=True, max_length=150)),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20)),
                ('pet_breed', models.CharField(blank=True, max_length=100)),
                ('pet_age', models.CharField(blank=True, max_length=100)),
                ('pet_sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('pet_neutered', models.BooleanField(default=False)),
                ('pet_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('consultation_goals', models.TextField(blank=True)),
                ('consultation_focus', models.TextField(blank=True, help_text='Comma-separated focus areas selected by the pet parent')),
                ('additional_notes', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('access_granted', 'Access Granted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
