# Generated by Django 6.0.2 on 2026-02-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_adminslaconfig_appointment_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appt_type',
            field=models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('vaccination', 'Vaccination'), ('surgery', 'Surgery'), ('follow_up', 'Follow-up'), ('grooming', 'Grooming'), ('wellness', 'Wellness Check'), ('emergency', 'Emergency'), ('other', 'Other')], default='consultation', max_length=30, verbose_name='Appointment Type'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_notes',
            field=models.TextField(blank=True, verbose_name='Reason / Notes'),
        ),
    ]
